apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-go
  labels:
    app: hello-world-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-go
  template:
    metadata:
      labels:
        app: hello-world-go
    spec:
      containers:
      - name: app
        image: osherachamim/hello-world-go:v1
        ports:
        - containerPort: 8080
