apiVersion: v1
kind: Service
metadata:
  name: hello-world-go-svc
  labels:
    app: hello-world-go
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-go
  type: NodePort 
